"""empty message

Revision ID: 95c3b72d00e7
Revises: f98660c7cf1d
Create Date: 2019-12-09 20:38:11.380987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c3b72d00e7'
down_revision = 'f98660c7cf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conten', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_comment')
    # ### end Alembic commands ###
